import nodemailer from "nodemailer";

let transporter = null;

/**
 * Read and validate the SMTP configuration.
 *
 * SMTP credentials must be supplied through environment variables.
 * Never place real email passwords or provider secrets in this file.
 */
function getMailConfiguration() {
  const host = process.env.SMTP_HOST?.trim();
  const portValue = process.env.SMTP_PORT?.trim();
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const from = process.env.MAIL_FROM?.trim();

  if (!host || !portValue || !user || !pass || !from) {
    throw new Error(
      "Email configuration is incomplete. Configure SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, and MAIL_FROM."
    );
  }

  const port = Number(portValue);

  if (
    !Number.isInteger(port) ||
    port < 1 ||
    port > 65535
  ) {
    throw new Error("The configured SMTP port is invalid.");
  }

  const secureSetting = process.env.SMTP_SECURE;

  let secure;

  if (secureSetting === "true") {
    secure = true;
  } else if (secureSetting === "false") {
    secure = false;
  } else if (secureSetting === undefined || secureSetting === "") {
    secure = port === 465;
  } else {
    throw new Error(
      "SMTP_SECURE must be set to true or false."
    );
  }

  if (port === 465 && !secure) {
    throw new Error(
      "Port 465 requires secure SMTP connections."
    );
  }

  return {
    host,
    port,
    secure,
    auth: {
      user,
      pass,
    },
    from,
  };
}

/**
 * Create the SMTP transporter when it is first needed.
 *
 * The transporter is reused for subsequent emails.
 */
function getTransporter() {
  if (transporter) {
    return transporter;
  }

  const config = getMailConfiguration();

  transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: config.auth,
    connectionTimeout: 10000,
    greetingTimeout: 10000,
    socketTimeout: 20000,
  });

  return transporter;
}

/**
 * Escape text before placing it inside HTML.
 */
function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (character) => {
    const entities = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    };

    return entities[character];
  });
}

/**
 * Send an account password-reset email.
 *
 * @param {object} options
 * @param {string} options.to - Recipient's email address.
 * @param {string} options.resetUrl - Complete reset URL generated by the server.
 *
 * The caller must generate a cryptographically random, single-use,
 * expiring reset token and construct the reset URL using a trusted
 * application origin.
 */
export async function sendPasswordResetEmail({
  to,
  resetUrl,
}) {
  if (
    typeof to !== "string" ||
    !to.trim() ||
    typeof resetUrl !== "string" ||
    !resetUrl.trim()
  ) {
    throw new TypeError(
      "A recipient email address and reset URL are required."
    );
  }

  let parsedUrl;

  try {
    parsedUrl = new URL(resetUrl);
  } catch {
    throw new TypeError("The password-reset URL is invalid.");
  }

  if (
    parsedUrl.protocol !== "https:" &&
    parsedUrl.hostname !== "localhost"
  ) {
    throw new TypeError(
      "Password-reset URLs must use HTTPS, except on localhost."
    );
  }

  const config = getMailConfiguration();
  const mailTransporter = getTransporter();

  const safeResetUrl = escapeHtml(parsedUrl.href);

  const message = {
    from: config.from,
    to: to.trim(),
    subject: "Reset your KeyCrove password",
    text: [
      "We received a request to reset your KeyCrove account password.",
      "",
      "Use the following link to continue:",
      parsedUrl.href,
      "",
      "If you did not request this, you can ignore this email.",
      "For your security, the reset link should expire and work only once.",
      "",
      "KeyCrove Security",
    ].join("\n"),
    html: `
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>Reset your KeyCrove password</title>
        </head>
        <body style="margin:0;padding:0;background:#080808;color:#ffffff;font-family:Arial,Helvetica,sans-serif;">
          <div style="max-width:560px;margin:0 auto;padding:40px 20px;">
            <div style="background:#111111;border:1px solid #292929;border-radius:16px;padding:32px;">
              <p style="margin:0 0 12px;color:#D4AF37;font-size:12px;font-weight:bold;letter-spacing:3px;">
                KEYCROVE SECURITY
              </p>

              <h1 style="margin:0 0 18px;font-size:26px;line-height:1.3;">
                Reset your password
              </h1>

              <p style="margin:0 0 24px;color:#A7A7A7;font-size:15px;line-height:1.8;">
                We received a request to reset your KeyCrove account password.
                If you made this request, use the button below to continue.
              </p>

              <p style="margin:0 0 28px;">
                <a
                  href="${safeResetUrl}"
                  style="display:inline-block;padding:14px 22px;background:#D4AF37;color:#080808;text-decoration:none;font-weight:bold;border-radius:8px;"
                >
                  Reset password
                </a>
              </p>

              <p style="margin:0 0 12px;color:#A7A7A7;font-size:13px;line-height:1.7;">
                If the button does not work, copy this address into your browser:
              </p>

              <p style="margin:0 0 24px;overflow-wrap:anywhere;font-size:12px;line-height:1.7;">
                <a href="${safeResetUrl}" style="color:#F1D77A;">
                  ${safeResetUrl}
                </a>
              </p>

              <div style="height:1px;background:#292929;margin:24px 0;"></div>

              <p style="margin:0;color:#A7A7A7;font-size:12px;line-height:1.8;">
                If you did not request a password reset, ignore this email.
                Never share your reset link with anyone.
              </p>
            </div>

            <p style="margin:20px 0 0;text-align:center;color:#777777;font-size:12px;">
              KeyCrove &mdash; Your digital security matters.
            </p>
          </div>
        </body>
      </html>
    `,
  };

  const result = await mailTransporter.sendMail(message);

  return {
    messageId: result.messageId,
    accepted: result.accepted,
    rejected: result.rejected,
  };
}

/**
 * Verify that the configured SMTP server can be reached
 * and that the connection settings are valid.
 *
 * This checks the mail transport, not whether a particular
 * recipient will receive an email.
 */
export async function verifyMailConnection() {
  const mailTransporter = getTransporter();

  await mailTransporter.verify();

  return true;
}
